spring.datasource.url=jdbc:postgresql://localhost:5432/print-calculator
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml
server.servlet.context-path=/api

